# Generated by Django 4.2.3 on 2023-08-16 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_remove_orderitem_order_orderitem_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='Order',
            new_name='order',
        ),
    ]
